#!/bin/bash

# Function to get the Git project name from the URL
git_project_name() {
    # Get the Git project name from the URL
    local url="$1"
    local project_name=$(basename "$url" .git)
    echo "$project_name"
}


#####################################################################################
# Function to read system.cfg file and export the key-value pairs found
#####################################################################################
export_system_cfg() {
    if [ ! -f "$HOME/.sensor_core/system.cfg" ]; then
        echo "Error: system.cfg file is missing in $HOME/.sensor_core"
        exit 1
    fi
    dos2unix -q "$HOME/.sensor_core/system.cfg" || { echo "Failed to convert system.cfg to Unix format"; exit 1; }
    while IFS='=' read -r key value; do
        if [[ $key != \#* && $key != "" ]]; then
            if [[ $key =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
                # Strip surrounding quotes from the value
                value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
                export "$key"="$value"
            else
                echo "Warning: Skipping invalid key '$key' in system.cfg"
            fi
        fi
    done < "$HOME/.sensor_core/system.cfg"

    # Append the git project name to the my_code_dir variable
    if [ -n "$my_git_repo_url" ]; then
        my_code_dir="$my_code_dir/$(git_project_name "$my_git_repo_url")"
    fi
}

#####################################################################################
# Activate the virtual environment
#####################################################################################
export_system_cfg
# Check if the virtual environment directory exists
if [ -d "$HOME/$venv_dir" ]; then
    # Activate the virtual environment
    source "$HOME/$venv_dir/bin/activate"
else
    echo "Error: Virtual environment not found at $HOME/$venv_dir"
    exit 1
fi

#####################################################################################
# Run the CLI
#####################################################################################
cd "$HOME/$my_code_dir"
python -m sensor_core.bcli menu
