name: venv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - azure-storage-blob
  - click
  - python-crontab
  - gitpython
  - numpy
  - pandas
  - psutil
  - pydantic-settings
  - pytest
  - python3-picamera2
  - PyYAML
  - scikit-learn
  - scipy
  - smbus2
  - pip
  - pip:
    - gpiozero
    - systemd-python
    - opencv-python
build:
  script: |
    echo "Using system site packages"
    conda env config vars set PYTHONNOUSERSITE=False
